name: ci

on:
  pull_request:
  push:
    branches: [main]
    tags: ['*']

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: { node-version: 14 }
      - run: yarn --frozen-lockfile
      - run: yarn eslint .

  jest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: { node-version: '${{ matrix.node-version }}' }
      - run: yarn --frozen-lockfile
      - run: yarn jest

  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: { node-version: 14 }
      - run: yarn --frozen-lockfile
      - run: yarn workspace eslint-config-remcohaszing pack
      - run: mv eslint-config/*.tgz ./
      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: '*.tgz'

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: { node-version: 14 }
      - run: yarn --frozen-lockfile
      - run: yarn prettier --check .

  release:
    runs-on: ubuntu-latest
    needs: [eslint, jest, pack, prettier, tsc]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/setup-node@v2
        with: { node-version: 14 }
      - uses: actions/download-artifact@v2
        with: { name: package }
      - run: ls
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
